---
- name: install apache2
  apt:
      name: apache2
      state: present
- name: remove file
  file:
       path: /var/www/html/
       state: absent

- name: git checkout
  git:
      repo: "{{git_url}}"
      dest: /var/www/html/
- name: start apache2
  service: 
        name: apache2
        state: started
# tasks file for apache2
